### PR TITLE
Incorporating changes from @tboerger and PR #6.

### PR DESCRIPTION
**Pull request by gtaylor**
Manually picking out some changes from #6 that were less controversial. We should probably address the others separately, as there was some argument over their specifics and necessity.

### CODE REVIEW

**Comment by msteinert** [comment]
LGTM

**Comment by tboerger** [comment]
So what is the goal? To just update DOCS.md like you wish it?

**Comment by gtaylor** [comment]
@tboerger No, that's why we're going through the review process.

**Comment by gtaylor** [comment]
LGTM

**Comment by gtaylor** [comment]
@bradrydzewski Can I troll for an LGTM?

As a side note, we don't have enough Python users to get two LGTMs on the two Python Drone plugins (this one and [drone-devpi](https://github.com/drone-plugins/drone-devpi)). I'd propose requiring one LGTM until we get more actual Python users involved.

**Comment by tboerger** [comment]
We should close this PR since further development happens on https://github.com/drone-python/plugin-pypi

**Comment by tboerger** [comment]
Thank you for your work, finally I merged https://github.com/drone-plugins/drone-pypi/pull/16 to get this plugin working for drone >= 0.5

**Pull request closed without merging**
