### PR TITLE
Improve CI test coverage

### PR DESCRIPTION
**Pull request by msteinert**
This change links in a container running [simplepypi][] in order to exercise the upload functionality during CI testing.

[simplepypi]: https://github.com/steiza/simplepypi

### CODE REVIEW

**Comment by bradrydzewski** [comment]
LGTM

**Comment by tboerger** [comment]
Where are those env variables used?

**Comment by msteinert** [comment]
https://github.com/drone-plugins/drone-pypi/blob/master/main_test.go#L35-L44

This changes improves test coverage during the CI build from 37% to 76%.

**Comment by tboerger** [comment]
> https://github.com/drone-plugins/drone-pypi/blob/master/main_test.go#L35-L44
> 
> This changes improves test coverage during the CI build from 37% to 76%.

Ah, thanks.
LGTM

**Pull request merged**
