### PR TITLE
Adding Gitter badge for drone/drone-python.

### PR DESCRIPTION
**Pull request by gtaylor**
Might as well.

### CODE REVIEW

**Comment by msteinert** [comment]
LGTM

**Comment by tboerger** [comment]
IMHO we should not link the client library specific gitter chats within the plugins.

**Comment by gtaylor** [comment]
Don't have too many Python folks, so I'm going to LGTM myself

**Comment by gtaylor** [comment]
It's in the same ecosystem. This and the devpi plugins are bedrock pieces.

**Comment by tboerger** [comment]
If you link to the main channel OK, but that's not really useful as most people will use drone and not directly develop

**Comment by nlf** [comment]
lgtm

i tend to agree with @gtaylor here, sending them to the most specific available chat makes sense.

**Comment by gtaylor** [comment]
This has been done in the new drone-python/plugin-devpi repo, from which new development will occur:

https://github.com/drone-python/plugin-pypi/commit/2fdf294242e100c32731a6650965f03a4f009ad7

We'll be diverging from this repo substantially, and probably rewriting in Python. Closing this issue!

**Comment by tboerger** [comment]
I would suggest a transfer ownership action, than there is no confusion about the correct repo and all requests to the old repo (this repo) will be redirected to the new one.

**Comment by gtaylor** [comment]
As discussed, going to leave this one as-is so as to not disturb any 0.4 users. We've renamed on the other end as well.

**Pull request closed without merging**
